#!/usr/bin/env bash

export CMDR_SRC_DIR=$(cd $(dirname $0) && pwd)
. "$CMDR_SRC_DIR/common"

if [ ! -d "$CMDR_SRC_DIR/logs" ]; then
  mkdir "$CMDR_SRC_DIR/logs"
fi

cmdr_help() {
    cmdr_help_header
    echo "\
    Commands:
       -e, --edit       Edit commands file
       -g, --grep       Grep for a particular command
       -x, --execute    Execute a set of commands
       -s, --source     Source a set of commands
       -l, --history    Show commands history
       -V, --version    Print version
       -h, --help       Display this help
    "
}

case "$1" in
  --grep | -g)
    "$CMDR_SRC_DIR/actions/grep" "$2" | tee -ia "$CMDR_SRC_DIR/logs/grep.log"
    ;;
  --edit | -e)
    $CMDR_EDITOR $CMDR_COMMANDS_FILE
    ;;
  --history | -l)
    $CMDR_EDITOR $CMDR_HISTORY_FILE
    ;;
  --version | -V)
    echo $(cat $CMDR_SRC_DIR/VERSION)
    ;;
  --help | -h)
    cmdr_help
    ;;
  *)
    cmdr_raise_error "Unknown command: $1
    See help with: cmdr --help"
    ;;
esac
