#!/usr/bin/env bash

set -e
. "$CMDR_SRC_DIR/utils"
. "$CMDR_SRC_DIR/actions/common"

cmdr_help_edit() {
    cmdr_help_header
    echo "\
    Command: --edit | -x [regex]
    Description: Execute a set of commands
    "
    exit 0
}

[ ! -n "$1" ] && cmdr_help_edit

cmdr_grep_commands "$1"

selected_cmds=$(cmdr_select_commands "$cmds")

echo "$selected_cmds" > $CMDR_EXECUTE_FILE

cmdr_save_history "$selected_cmds"

chmod +x $CMDR_EXECUTE_FILE
$CMDR_EXECUTE_FILE

