#!/usr/bin/env bash

set -e
. "$CMDR_SRC_DIR/utils"
. "$CMDR_SRC_DIR/actions/common"

cmdr_help_grep() {
    cmdr_help_header
    echo "\
    Command: --grep | -g [regex]
    Description: Grep for a particular command
    "
    exit 0
}

[ ! -n "$1" ] && cmdr_help_grep

cmdr_grep_commands "$1"

# Write all commands to last.log
cmdr_save_history "$cmds"
